name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  check-starters:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Check starters
        run: yarn check-starters