name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ensure-only-starters-changed:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Ensure only starters file have changed
        run: yarn ensure-only-starters-changed