name: Node.js CI

on: 
  push:
    branches: [ main ]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Setup git
        run: |
          git config --global user.email "hi@aGuyNamedJonas.com"
          git config --global user.name "startmeup's publish bot"
      - name: Install & Test
        run: |
          npm install
          npm test
      - name: Add starters to README
        run: |
          npm run add-starters-to-readme
      - name: Build new package version
        run: |
          rm -r ./bin -f
          npm run prepare
          npm version patch
          npm publish --access public
      - name: Push new README & package version change back to repo
        run: |
          git add README.md
          git commit -m 'Update starters in README.md'
          git push origin HEAD:main
