name: Node.js CI

on: 
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Setup git
        run: |
          git config --global user.email "hi@aGuyNamedJonas.com"
          git config --global user.name "startmeup's publish bot"
      - name: Install & Test
        run: |
          npm install
          npm test
      - name: Add starters to README
        run: npm run add-starters-to-readme
      - name: Push new README back to repo
        run: git add README.md
        run: git commit -m 'Update starters in README.md'
        run: git push origin HEAD:main
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Build & publish startmeup
        run: |
        rm -r ./bin -f
        npm run prepare
        npm version patch
